
export const metadata = {
  title:{
    
    default:"Learning Routing ",
    template:"%s | Next.js Project",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:'lightblue',
          padding:"1rem",
        }}><p>This is a header</p></header>
        {children}
        <footer style={{backgroundColor:'lightgreen',
          padding:"1rem",
        }}><p>This is a footer</p></footer>
        </body>

    </html>
  )
}
